version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: techmart-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: techmart123
      MONGO_INITDB_DATABASE: techmart_customers
    volumes:
      - mongodb_data:/data/db
      - mongodb_config:/data/configdb
      - ./mongodb_init_scripts:/docker-entrypoint-initdb.d:ro
    networks:
      - techmart-network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.admin.runCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

volumes:
  mongodb_data:
    driver: local
  mongodb_config:
    driver: local

networks:
  techmart-network:
    driver: bridge
